# Generated by Django 4.2 on 2023-06-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyWorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LongTermPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='permit_photos')),
                ('applicant_name', models.CharField(max_length=100)),
                ('employer_name', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('trainee_at_expiry', models.CharField(max_length=100)),
                ('long_term_trainee', models.CharField(max_length=100)),
                ('condition', models.TextField()),
                ('variation_of_conditions', models.TextField()),
                ('authorized_officer', models.CharField(max_length=100)),
                ('permit_number', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitersLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExemptionPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
