# Generated by Django 4.2 on 2023-06-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermpermit',
            name='photo',
        ),
    ]
