# Generated by Django 4.2 on 2023-06-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_remove_longtermpermit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermpermit',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
