# Generated by Django 4.2 on 2023-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Omang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Number', models.CharField(max_length=9)),
                ('surname', models.CharField(max_length=200)),
                ('forenames', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_expiry', models.DateField()),
                ('colour_of_eyes', models.CharField(max_length=200)),
                ('place_of_application', models.CharField(max_length=200)),
            ],
        ),
    ]
